### ISSUE TITLE
Standards and system boundary

### ISSUE THREAD

**Issue by viktoriasee** [AndyClifton/accessibility#36]
This package so far tries to tag PDFs and include relevant metadata. However, there are different standards for accessibility: [PDF/A](https://en.wikipedia.org/wiki/PDF/A-na) and [PDF/UA](https://en.wikipedia.org/wiki/PDF/UA)
PDF/A-nb (n being 1 to 3 currently) does not target accessibility but requires metadata that are similar or identical to what we need here. PDF/X requires lots of stuff PDF/A needs but not the tagging.
To make long ends meet maybe it's a good idea to solve tagging in a separate package and use accessibility only for metadata, alternative texts and the like. Tagging is the difficult part. There is already such a package but it's not automatic: [tagpdf](https://github.com/u-fischer/tagpdf)

PDF/A3 sounds interesting for LaTeX since you can include the source code in the document. Just the other way round of what LaTeX did with the docstrip dtx files many, many years ago.

**Comment by AndyClifton** [comment]
Moving this in to the refactor project as I think this is an important part of scoping.

**Comment by viktoriasee** [comment]
When we talk about fundraising and future plans (#42) I identify different needs
 1. Package for colour management. This could be used also without accessibility for PDF/X compliance. But it is mandatory for PDF/A, all levels a, b and u
 1. Package for automated tagging
    1. minimal function: Tag images and equations only and provide a way to add alternative descriptions.
    1. full function: Automatic tagging of all relevant content. Backgrounds and fold marks are non-relevant content and should be tagged as artifacts.

**Comment by AndyClifton** [comment]
For anyone stumbling in here or wondering why this issue is closed, the question of accessibility in PDFs has now been taken up by the LaTeX project in a multiyear project and as a result I am stopping work on this package. See https://www.latex-project.org/publications/indexbytopic/pdf/ for news.

The article, ["LaTeX Tagged PDF — A blueprint for a large project"](https://www.latex-project.org/publications/2020-FMi-TUB-tb129mitt-tagpdf.pdf) may be particularly useful.
